include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
