"""initial_schema

Revision ID: d3422e549143
Revises: 
Create Date: 2026-02-25 23:34:10.968242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3422e549143'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speaking_style', sa.String(length=200), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('catchphrase', sa.String(length=200), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=50), nullable=True),
    sa.Column('emoji_usage', sa.String(length=50), nullable=True),
    sa.Column('humor_level', sa.String(length=50), nullable=True),
    sa.Column('formality', sa.String(length=50), nullable=True),
    sa.Column('empathy_level', sa.String(length=50), nullable=True),
    sa.Column('knowledge_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_agent_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice_style', sa.String(length=100), nullable=True),
    sa.Column('voice_speed', sa.String(length=50), nullable=True),
    sa.Column('animation_set', sa.String(length=100), nullable=True),
    sa.Column('response_length', sa.String(length=50), nullable=True),
    sa.Column('encouragement_style', sa.String(length=200), nullable=True),
    sa.Column('teaching_approach', sa.String(length=200), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'PARENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('parent_of', sa.UUID(), nullable=True),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_of'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classroom_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'TRANSCRIBING', 'SUMMARIZING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_sessions_user_id'), 'classroom_sessions', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('ACADEMIC', 'CLASSROOM', 'EMOTIONAL', 'HEALTH', 'CREATIVE', 'CAREER', name='agenttype'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('exercise_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_plans_user_id'), 'exercise_plans', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ABANDONED', name='goalstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='goalpriority'), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('smart_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('gratitude_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gratitude_entries_user_id'), 'gratitude_entries', ['user_id'], unique=False)
    op.create_table('health_reminders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reminder_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('forced_break_minutes', sa.Integer(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('eye_rest_enabled', sa.Boolean(), nullable=False),
    sa.Column('exercise_enabled', sa.Boolean(), nullable=False),
    sa.Column('posture_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reminders_user_id'), 'health_reminders', ['user_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('total_stages', sa.Integer(), nullable=False),
    sa.Column('interest_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('persona_memory_entries',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_memory_entries_persona_id'), 'persona_memory_entries', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_memory_entries_user_id'), 'persona_memory_entries', ['user_id'], unique=False)
    op.create_table('progress_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.String(length=20), nullable=False),
    sa.Column('period_end', sa.String(length=20), nullable=False),
    sa.Column('completion_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deviation_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_reports_user_id'), 'progress_reports', ['user_id'], unique=False)
    op.create_table('screen_time_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('face_distance_cm', sa.Float(), nullable=True),
    sa.Column('continuous_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_time_records_user_id'), 'screen_time_records', ['user_id'], unique=False)
    op.create_table('user_learning_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_level', sa.String(length=20), nullable=False),
    sa.Column('weak_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('study_habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_study_hours', sa.Float(), nullable=False),
    sa.Column('total_questions_answered', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_profiles_user_id'), 'user_learning_profiles', ['user_id'], unique=True)
    op.create_table('user_persona_bindings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_persona_bindings_user_id'), 'user_persona_bindings', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ability_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interest_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotion_baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('classroom_doubts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_start', sa.Float(), nullable=False),
    sa.Column('timestamp_end', sa.Float(), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('doubt_type', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_doubts_session_id'), 'classroom_doubts', ['session_id'], unique=False)
    op.create_table('crisis_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('alert_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertlevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_content', sa.Text(), nullable=False),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notified_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crisis_alerts_status'), 'crisis_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_crisis_alerts_user_id'), 'crisis_alerts', ['user_id'], unique=False)
    op.create_table('emotion_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('emotion_label', sa.Enum('HAPPY', 'ANXIOUS', 'DEPRESSED', 'CALM', 'ANGRY', 'SAD', 'FEARFUL', name='emotionlabel'), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('arousal', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('TEXT', 'VOICE', 'VISUAL', 'FUSED', name='emotionsource'), nullable=False),
    sa.Column('raw_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_records_user_id'), 'emotion_records', ['user_id'], unique=False)
    op.create_table('learning_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.Enum('MATH', 'PHYSICS', 'CHEMISTRY', 'CHINESE', 'ENGLISH', 'BIOLOGY', 'HISTORY', 'GEOGRAPHY', 'POLITICS', name='subject'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('knowledge_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_subject'), 'learning_records', ['subject'], unique=False)
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'FILE', name='contenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('intent_label', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=30), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('review_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_session_id'), 'study_plans', ['session_id'], unique=False)
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('error_records',
    sa.Column('learning_record_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'PHYSICS', 'CHEMISTRY', 'CHINESE', 'ENGLISH', 'BIOLOGY', 'HISTORY', 'GEOGRAPHY', 'POLITICS', name='subject'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('wrong_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Enum('CONCEPT_MISUNDERSTANDING', 'WRONG_APPROACH', 'MISREAD_QUESTION', 'CALCULATION_ERROR', name='errortype'), nullable=False),
    sa.Column('error_analysis', sa.Text(), nullable=True),
    sa.Column('knowledge_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mastery_status', sa.Enum('WEAK', 'IMPROVING', 'MASTERED', name='masterystatus'), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('recommended_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_record_id'], ['learning_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_records_learning_record_id'), 'error_records', ['learning_record_id'], unique=False)
    op.create_index(op.f('ix_error_records_subject'), 'error_records', ['subject'], unique=False)
    op.create_index(op.f('ix_error_records_user_id'), 'error_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_records_user_id'), table_name='error_records')
    op.drop_index(op.f('ix_error_records_subject'), table_name='error_records')
    op.drop_index(op.f('ix_error_records_learning_record_id'), table_name='error_records')
    op.drop_table('error_records')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_session_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_subject'), table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_emotion_records_user_id'), table_name='emotion_records')
    op.drop_table('emotion_records')
    op.drop_index(op.f('ix_crisis_alerts_user_id'), table_name='crisis_alerts')
    op.drop_index(op.f('ix_crisis_alerts_status'), table_name='crisis_alerts')
    op.drop_table('crisis_alerts')
    op.drop_index(op.f('ix_classroom_doubts_session_id'), table_name='classroom_doubts')
    op.drop_table('classroom_doubts')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_persona_bindings_user_id'), table_name='user_persona_bindings')
    op.drop_table('user_persona_bindings')
    op.drop_index(op.f('ix_user_learning_profiles_user_id'), table_name='user_learning_profiles')
    op.drop_table('user_learning_profiles')
    op.drop_index(op.f('ix_screen_time_records_user_id'), table_name='screen_time_records')
    op.drop_table('screen_time_records')
    op.drop_index(op.f('ix_progress_reports_user_id'), table_name='progress_reports')
    op.drop_table('progress_reports')
    op.drop_index(op.f('ix_persona_memory_entries_user_id'), table_name='persona_memory_entries')
    op.drop_index(op.f('ix_persona_memory_entries_persona_id'), table_name='persona_memory_entries')
    op.drop_table('persona_memory_entries')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_health_reminders_user_id'), table_name='health_reminders')
    op.drop_table('health_reminders')
    op.drop_index(op.f('ix_gratitude_entries_user_id'), table_name='gratitude_entries')
    op.drop_table('gratitude_entries')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_exercise_plans_user_id'), table_name='exercise_plans')
    op.drop_table('exercise_plans')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_classroom_sessions_user_id'), table_name='classroom_sessions')
    op.drop_table('classroom_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('personas')
    # ### end Alembic commands ###
