// GENERATED CODE - DO NOT MODIFY BY HAND

// This is a temporary manual stub. Run build_runner to regenerate.
// dart run build_runner build --delete-conflicting-outputs

import 'package:get_it/get_it.dart';

extension GetItInjectableX on GetIt {
  void init() {
    // Will be auto-generated by injectable_generator
    // For now, manual registration happens in bootstrap.dart
  }
}
